--参数设置
----产品分类
CREATE TABLE POSS_PROD_TYPE  (
   ID_                  VARCHAR2(36)                    NOT NULL,
   PROD_TYPE_           VARCHAR2(64),
   DISPLAY_ORDER_	INTEGER,
   PARENT_ID_           VARCHAR2(36),
   REMARK_              VARCHAR2(512),
   CONSTRAINT PK_POSS_PROD_TYPE PRIMARY KEY (ID_)
);

--公共
----附件
/*==============================================================*/
/* Table: POSS_ATTACHMENT                                       */
/*==============================================================*/
CREATE TABLE POSS_ATTACHMENT  (
   ID_                  VARCHAR2(36)                    NOT NULL,
   FILE_EXT_            VARCHAR2(36),
   FELE_PATH_           VARCHAR2(512),
   DISPLAY_NAME_        VARCHAR2(128),
   SIZE_                INTEGER,
   UPLOAD_DATE_         TIMESTAMP,
   CONSTRAINT PK_POSS_ATTACHMENT PRIMARY KEY (ID_)
);

--运营管理
----退款须知
/*==============================================================*/
/* Table: POSS_REFUNC_NOTICE                                    */
/*==============================================================*/
CREATE TABLE POSS_REFUNC_NOTICE  (
   ID_                  VARCHAR2(36)                    NOT NULL,
   TRUST_COMPANY_       VARCHAR2(128),
   REFUND_NOTICE_       VARCHAR2(512),
   LINKMAN_             VARCHAR2(36),
   CREATE_TIME_         TIMESTAMP,
   CONSTRAINT PK_POSS_REFUNC_NOTICE PRIMARY KEY (ID_)
);

--退款须知附件
/*==============================================================*/
/* Table: POSS_NOTICE_ATTACH                                    */
/*==============================================================*/
CREATE TABLE POSS_NOTICE_ATTACH  (
   REFUND_NOTICE_ID     VARCHAR2(36)                    NOT NULL,
   ATTACH_ID_           VARCHAR2(36)                    NOT NULL,
   CONSTRAINT PK_POSS_NOTICE_ATTACH PRIMARY KEY (REFUND_NOTICE_ID, ATTACH_ID_)
);

COMMENT ON TABLE POSS_NOTICE_ATTACH IS
'退款须知附件';

COMMENT ON COLUMN POSS_NOTICE_ATTACH.REFUND_NOTICE_ID IS
'须知ID';

COMMENT ON COLUMN POSS_NOTICE_ATTACH.ATTACH_ID_ IS
'附件ID';

ALTER TABLE POSS_NOTICE_ATTACH
   ADD CONSTRAINT FK_POSS_NOT_REFERENCE_POSS_REF FOREIGN KEY (REFUND_NOTICE_ID)
      REFERENCES POSS_REFUNC_NOTICE (ID_);

ALTER TABLE POSS_NOTICE_ATTACH
   ADD CONSTRAINT FK_POSS_NOT_REFERENCE_POSS_ATT FOREIGN KEY (ATTACH_ID_)
      REFERENCES POSS_ATTACHMENT (ID_);

--供应商
CREATE TABLE POSS_SUPPLIER  (
   ID_                  VARCHAR2(36)                    NOT NULL,
   SUPPLIER_            VARCHAR2(128),
   REMARK_              VARCHAR2(512),
   CONSTRAINT PK_POSS_SUPPLIER PRIMARY KEY (ID_)
);

--产品信息
CREATE TABLE POSS_PROD_INFO
(
  ID_                       VARCHAR2(36) NOT NULL,
  PROD_SECONDARY_CLASSIFY_  VARCHAR2(36),
  PROD_TYPE_                VARCHAR2(64),
  PROD_CODE_                VARCHAR2(36),
  PROD_NAME_                VARCHAR2(128),
  FINANCE_COMPANY_NAME_     VARCHAR2(128),
  PROD_STATUS_              VARCHAR2(64),
  SUPPLIER_                 VARCHAR2(36),
  PJT_TOTAL_AMOUNT_         NUMBER(16,2),
  PJT_AMOUNT_REMARK_        VARCHAR2(512),
  SELL_AMOUNT_              NUMBER(16,2),
  SELL_TIME_LIMIT_          INTEGER,
  TIME_LIMIT_REMARK_        VARCHAR2(512),
  SELL_RANK_                VARCHAR2(64),
  OPERATION_WARNING_        VARCHAR2(128),
  SELL_DATE_                DATE,
  TRANSFER_DEADLINE_        DATE,
  RAISE_FUNDS_END_TIME_     DATE,
  PROD_SET_UP_DATE_         DATE,
  PROD_CASH_DATE_           DATE,
  ACTUAL_CASH_DATE_         DATE,
  PAY_INTEREST_METHOD_      VARCHAR2(128),
  TRUST_BANK_               VARCHAR2(128),
  RAISE_BANK_               VARCHAR2(128),
  RAISE_ACCOUNT_            VARCHAR2(128),
  JANE_EDITION_ATTCH_       VARCHAR2(36),
  OTHER_EDITION_ATTCH_      VARCHAR2(36),
  PROD_MANAGER_             VARCHAR2(36),
  PROD_MANAGER_TEL_         VARCHAR2(64),
  PROD_MANAGER_EMAIL_       VARCHAR2(64),
  PROD_SUPERVISOR_          VARCHAR2(36),
  SUPERVISOR_CONTACT_WAY_   VARCHAR2(64),
  SUPERVISOR_REMARK_        VARCHAR2(512),
  EXPECT_SELL_DATE_         DATE,
  OPERATION_PERIOD_         VARCHAR2(64),
  TOTAL_APPOINTMENT_AMOUNT_ NUMBER(16,2),
  TRANSFER_AMOUNT_          NUMBER(16,2),
  TO_ACCOUNT_AMOUNT_        NUMBER(16,2),
  TO_ACCOUNT_SMALL_AMOUNT_  NUMBER(4),
  NEED_GRADE_FLAG_          INTEGER DEFAULT 0,
  VIDEO_LECTURES_           VARCHAR2(36),
  CREATOR_                  VARCHAR2(36),
  CREATE_TIME_              TIMESTAMP(6),
  ACCOUNTING_COEFFICIENT_   NUMBER(16,5),
  REMAIN_AMOUNT_        		NUMBER(16,2),
  REDEEM_FLAG_        		INTEGER default 0,
  CONSTRAINT PK_POSS_PROD_INFO PRIMARY KEY (ID_)
);
-- ADD COMMENTS TO THE TABLE 
COMMENT ON TABLE POSS_PROD_INFO
  IS '产品信息';
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN POSS_PROD_INFO.ID_
  IS '主键';
COMMENT ON COLUMN POSS_PROD_INFO.PROD_SECONDARY_CLASSIFY_
  IS '固定收益
浮动收益';
COMMENT ON COLUMN POSS_PROD_INFO.PROD_TYPE_
  IS '参数设置';
COMMENT ON COLUMN POSS_PROD_INFO.PROD_CODE_
  IS '产品代码';
COMMENT ON COLUMN POSS_PROD_INFO.PROD_NAME_
  IS '产品名称';
COMMENT ON COLUMN POSS_PROD_INFO.FINANCE_COMPANY_NAME_
  IS '融资公司名称';
COMMENT ON COLUMN POSS_PROD_INFO.PROD_STATUS_
  IS '数据字典:产品发行、其它';
COMMENT ON COLUMN POSS_PROD_INFO.SUPPLIER_
  IS '供应商';
COMMENT ON COLUMN POSS_PROD_INFO.PJT_TOTAL_AMOUNT_
  IS '项目总额度';
COMMENT ON COLUMN POSS_PROD_INFO.PJT_AMOUNT_REMARK_
  IS '项目总客度备注';
COMMENT ON COLUMN POSS_PROD_INFO.SELL_AMOUNT_
  IS '发行额度';
COMMENT ON COLUMN POSS_PROD_INFO.SELL_TIME_LIMIT_
  IS '期限';
COMMENT ON COLUMN POSS_PROD_INFO.TIME_LIMIT_REMARK_
  IS '期限备注';
COMMENT ON COLUMN POSS_PROD_INFO.SELL_RANK_
  IS '销售级别';
COMMENT ON COLUMN POSS_PROD_INFO.OPERATION_WARNING_
  IS '运营预警';
COMMENT ON COLUMN POSS_PROD_INFO.SELL_DATE_
  IS '发行日期';
COMMENT ON COLUMN POSS_PROD_INFO.TRANSFER_DEADLINE_
  IS '停止划款时间';
COMMENT ON COLUMN POSS_PROD_INFO.RAISE_FUNDS_END_TIME_
  IS '募集结束日期';
COMMENT ON COLUMN POSS_PROD_INFO.PROD_SET_UP_DATE_
  IS '产品成立日期';
COMMENT ON COLUMN POSS_PROD_INFO.PROD_CASH_DATE_
  IS '产品兑付日期';
COMMENT ON COLUMN POSS_PROD_INFO.ACTUAL_CASH_DATE_
  IS '实际兑付日期';
COMMENT ON COLUMN POSS_PROD_INFO.PAY_INTEREST_METHOD_
  IS '付息方式';
COMMENT ON COLUMN POSS_PROD_INFO.TRUST_BANK_
  IS '托管行';
COMMENT ON COLUMN POSS_PROD_INFO.RAISE_BANK_
  IS '募集行';
COMMENT ON COLUMN POSS_PROD_INFO.RAISE_ACCOUNT_
  IS '募集账号';
COMMENT ON COLUMN POSS_PROD_INFO.JANE_EDITION_ATTCH_
  IS '简版附件';
COMMENT ON COLUMN POSS_PROD_INFO.OTHER_EDITION_ATTCH_
  IS '非简版附件';
COMMENT ON COLUMN POSS_PROD_INFO.PROD_MANAGER_
  IS '产品经理';
COMMENT ON COLUMN POSS_PROD_INFO.PROD_MANAGER_TEL_
  IS '产品经理联系电话';
COMMENT ON COLUMN POSS_PROD_INFO.PROD_MANAGER_EMAIL_
  IS '产品经理联系邮箱';
COMMENT ON COLUMN POSS_PROD_INFO.PROD_SUPERVISOR_
  IS '产品督导';
COMMENT ON COLUMN POSS_PROD_INFO.SUPERVISOR_CONTACT_WAY_
  IS '产品督导联系方式';
COMMENT ON COLUMN POSS_PROD_INFO.SUPERVISOR_REMARK_
  IS '备注';
COMMENT ON COLUMN POSS_PROD_INFO.EXPECT_SELL_DATE_
  IS '预计发行时间';
COMMENT ON COLUMN POSS_PROD_INFO.OPERATION_PERIOD_
  IS '运营周期';
COMMENT ON COLUMN POSS_PROD_INFO.TOTAL_APPOINTMENT_AMOUNT_
  IS '预约划款合计';
COMMENT ON COLUMN POSS_PROD_INFO.TRANSFER_AMOUNT_
  IS '划款金额';
COMMENT ON COLUMN POSS_PROD_INFO.TO_ACCOUNT_AMOUNT_
  IS '到账金额';
COMMENT ON COLUMN POSS_PROD_INFO.TO_ACCOUNT_SMALL_AMOUNT_
  IS '到账小额数';
COMMENT ON COLUMN POSS_PROD_INFO.NEED_GRADE_FLAG_
  IS '0 否 （默认0）
1 是';
COMMENT ON COLUMN POSS_PROD_INFO.VIDEO_LECTURES_
  IS '视频讲座';
COMMENT ON COLUMN POSS_PROD_INFO.CREATOR_
  IS '创建人';
COMMENT ON COLUMN POSS_PROD_INFO.CREATE_TIME_
  IS '创建时间';
COMMENT ON COLUMN POSS_PROD_INFO.ACCOUNTING_COEFFICIENT_
  IS '产品核算系数';
ALTER TABLE POSS_PROD_INFO
  ADD CONSTRAINT FK_PRO_JANE_REFERENCE_POSS_ATT FOREIGN KEY (JANE_EDITION_ATTCH_)
  REFERENCES POSS_ATTACHMENT (ID_);
ALTER TABLE POSS_PROD_INFO
  ADD CONSTRAINT FK_PRO_OTHE_REFERENCE_POSS_ATT FOREIGN KEY (OTHER_EDITION_ATTCH_)
  REFERENCES POSS_ATTACHMENT (ID_);

-- Create table
create table POSS_EXPECT_YEAR_YIELD
(
  id_          VARCHAR2(36) not null,
  prod_id_     VARCHAR2(36),
  lower_limit  NUMBER(16,2),
  upper_limit_ NUMBER(16,2),
  year_yield_  NUMBER(16,2),
  benefit_type VARCHAR2(64),
  CONSTRAINT PK_POSS_EXPECT_YEAR_YIELD PRIMARY KEY (ID_)
);
-- Add comments to the table 
comment on table POSS_EXPECT_YEAR_YIELD
  is '预期年化收益率';
-- Add comments to the columns 
comment on column POSS_EXPECT_YEAR_YIELD.id_
  is '主键';
comment on column POSS_EXPECT_YEAR_YIELD.prod_id_
  is '产品ID';
comment on column POSS_EXPECT_YEAR_YIELD.lower_limit
  is '下限';
comment on column POSS_EXPECT_YEAR_YIELD.upper_limit_
  is '上限';
comment on column POSS_EXPECT_YEAR_YIELD.year_yield_
  is '年化收益率';
comment on column POSS_EXPECT_YEAR_YIELD.benefit_type
  is '受益类别';
alter table POSS_EXPECT_YEAR_YIELD
  add constraint FK_POSS_EXP_REFERENCE_POSS_PRO foreign key (PROD_ID_)
  references POSS_PROD_INFO (ID_);

-- Create table
create table POSS_PROD_PAY_DATE
(
  id_              VARCHAR2(36) not null,
  prod_id_         VARCHAR2(36),
  expect_pay_date_ DATE,
  actual_pay_date_ DATE,
  CONSTRAINT PK_POSS_PROD_PAY_DATE PRIMARY KEY (ID_)
);
-- Add comments to the table 
comment on table POSS_PROD_PAY_DATE
  is '产品付息日期';
-- Add comments to the columns 
comment on column POSS_PROD_PAY_DATE.id_
  is '主键';
comment on column POSS_PROD_PAY_DATE.prod_id_
  is '产品ID';
comment on column POSS_PROD_PAY_DATE.expect_pay_date_
  is '预计付息日';
comment on column POSS_PROD_PAY_DATE.actual_pay_date_
  is '实际付息日';
alter table POSS_PROD_PAY_DATE
  add constraint FK_POSS_PRO_REFERENCE_POSS_PRO foreign key (PROD_ID_)
  references POSS_PROD_INFO (ID_);


--产品问答
create table POSS_PROD_FAQ
(
  id_          VARCHAR2(36) not null,
  prod_id_     VARCHAR2(36),
  title_       VARCHAR2(128),
  create_time_ TIMESTAMP(6),
  creator_     VARCHAR2(36),
  parent_id_   VARCHAR2(36),
  content_     VARCHAR2(4000),
  CONSTRAINT PK_POSS_PROD_FAQ PRIMARY KEY (ID_)
);
-- ADD COMMENTS TO THE TABLE 
COMMENT ON TABLE POSS_PROD_FAQ
  IS '产品问答';
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN POSS_PROD_FAQ.ID_
  IS '主键';
COMMENT ON COLUMN POSS_PROD_FAQ.PROD_ID_
  IS '产品ID';
COMMENT ON COLUMN POSS_PROD_FAQ.TITLE_
  IS '标题';
COMMENT ON COLUMN POSS_PROD_FAQ.CONTENT_
  IS '内容';
COMMENT ON COLUMN POSS_PROD_FAQ.CREATE_TIME_
  IS '时间';
COMMENT ON COLUMN POSS_PROD_FAQ.CREATOR_
  IS '提问人';
COMMENT ON COLUMN POSS_PROD_FAQ.PARENT_ID_
  IS '回复父ID';
  
ALTER TABLE POSS_PROD_FAQ
  ADD CONSTRAINT FK_PROD_FAQ_REFERENCE_POSS_PRO FOREIGN KEY (PROD_ID_)
  REFERENCES POSS_PROD_INFO (ID_);
ALTER TABLE POSS_PROD_FAQ
  ADD CONSTRAINT FK_PROD_FAQ_REFERENCE_PROD_FAQ FOREIGN KEY (PARENT_ID_)
  REFERENCES POSS_PROD_FAQ (ID_);

--短信
CREATE TABLE POSS_MESSAGE  (
   ID_                  VARCHAR2(36)                    NOT NULL,
   PROD_ID_             VARCHAR2(36),
   PROD_NAME_           VARCHAR2(128),
   TITLE_               VARCHAR2(128),
   CONTENT              CLOB,
   SEND_TIME_           TIMESTAMP(6),
   SEND_NO_             VARCHAR2(128),
   SALES_MANAGER_       VARCHAR2(36),
   RECEIVER_NO_         VARCHAR2(4000),
   CONSTRAINT PK_POSS_MESSAGE PRIMARY KEY (ID_)
);

COMMENT ON TABLE POSS_MESSAGE IS
'短信记录';

COMMENT ON COLUMN POSS_MESSAGE.ID_ IS
'主键';

COMMENT ON COLUMN POSS_MESSAGE.PROD_ID_ IS
'产品ID';

COMMENT ON COLUMN POSS_MESSAGE.PROD_NAME_ IS
'产品名称';

COMMENT ON COLUMN POSS_MESSAGE.TITLE_ IS
'标题';

COMMENT ON COLUMN POSS_MESSAGE.CONTENT IS
'内容';

COMMENT ON COLUMN POSS_MESSAGE.SEND_TIME_ IS
'时间';

COMMENT ON COLUMN POSS_MESSAGE.SEND_NO_ IS
'发送号码';

COMMENT ON COLUMN POSS_MESSAGE.SALES_MANAGER_ IS
'发送人';

COMMENT ON COLUMN POSS_MESSAGE.RECEIVER_NO_ IS
'接收号码';

ALTER TABLE POSS_MESSAGE
   ADD CONSTRAINT FK_POSS_MES_REFERENCE_POSS_PRO FOREIGN KEY (PROD_ID_)
      REFERENCES POSS_PROD_INFO (ID_);


/*==============================================================*/
/* Table: POSS_CUST_PAYMENT                                     */
/*==============================================================*/
CREATE TABLE POSS_CUST_PAYMENT  (
   ID_                  VARCHAR2(36)                    NOT NULL,
   PAY_TYPE_            VARCHAR2(36),
   PROD_ID_             VARCHAR2(36),
   CUST_ID_             VARCHAR2(36),
   CUST_NAME_           VARCHAR2(128),
   CUST_PROPERTY_       VARCHAR2(36),
   APPOINTMENT_AMOUNT_  NUMBER(16,2),
   PAY_DEPOSIT_FLAG_    SMALLINT,
   TRANSFER_AMOUNT_     NUMBER(16,2),
   TRANSFER_DATE_       DATE,
   REMARK_              VARCHAR2(256),
   PROPOSER_            VARCHAR2(36),
   PROPOSER_DEPT_       VARCHAR2(36),
   APPLY_TIME_          TIMESTAMP(6),
   PAYMENT_RECEIPT_ID_  VARCHAR2(36),
   FLOW_INSTANCE_ID_    VARCHAR2(36),
   ARCHIVE_DATE_        TIMESTAMP(6),
   PASSED_              SMALLINT,
   FORM_STATUS_         VARCHAR2(36),
   STANDARD_FLAG_		SMALLINT,
   SALE_MAN_ID_			VARCHAR2(36),
   APPOINTMENT_AMOUNT_CAPITAL_		VARCHAR2(128),
   TRANSFER_AMOUNT_CAPITAL_			VARCHAR2(128),
   IDENTITY_NUM         VARCHAR2(36),
   TOTAL_REFUND_AMOUNT_     NUMBER(16,2) default 0,
   CONSTRAINT PK_POSS_CUST_PAYMENT PRIMARY KEY (ID_)
);

COMMENT ON TABLE POSS_CUST_PAYMENT IS
'划款登记';

COMMENT ON COLUMN POSS_CUST_PAYMENT.ID_ IS
'主键';

COMMENT ON COLUMN POSS_CUST_PAYMENT.PAY_TYPE_ IS
'老客户划款
新客户划款
';
COMMENT ON COLUMN POSS_CUST_PAYMENT.STANDARD_FLAG_ IS
'0 否(默认)
1 是';

COMMENT ON COLUMN POSS_CUST_PAYMENT.PROD_ID_ IS
'产品ID';

COMMENT ON COLUMN POSS_CUST_PAYMENT.CUST_ID_ IS
'客户ID';

COMMENT ON COLUMN POSS_CUST_PAYMENT.CUST_NAME_ IS
'客户名称';

COMMENT ON COLUMN POSS_CUST_PAYMENT.CUST_PROPERTY_ IS
'客户性质';

COMMENT ON COLUMN POSS_CUST_PAYMENT.APPOINTMENT_AMOUNT_ IS
'预约金额';

COMMENT ON COLUMN POSS_CUST_PAYMENT.PAY_DEPOSIT_FLAG_ IS
'有无订金';

COMMENT ON COLUMN POSS_CUST_PAYMENT.TRANSFER_AMOUNT_ IS
'划款金额';

COMMENT ON COLUMN POSS_CUST_PAYMENT.TRANSFER_DATE_ IS
'预计/划款时间';

COMMENT ON COLUMN POSS_CUST_PAYMENT.REMARK_ IS
'备注';

COMMENT ON COLUMN POSS_CUST_PAYMENT.PROPOSER_ IS
'申请人';

COMMENT ON COLUMN POSS_CUST_PAYMENT.PROPOSER_DEPT_ IS
'所在部门';

COMMENT ON COLUMN POSS_CUST_PAYMENT.APPLY_TIME_ IS
'申请时间';

COMMENT ON COLUMN POSS_CUST_PAYMENT.PAYMENT_RECEIPT_ID_ IS
'打款凭条';

COMMENT ON COLUMN POSS_CUST_PAYMENT.FLOW_INSTANCE_ID_ IS
'流程实例ID';

COMMENT ON COLUMN POSS_CUST_PAYMENT.ARCHIVE_DATE_ IS
'归档时间';

COMMENT ON COLUMN POSS_CUST_PAYMENT.PASSED_ IS
'是否审批通过';

COMMENT ON COLUMN POSS_CUST_PAYMENT.FORM_STATUS_ IS
'流程结束时为已归档状态
用于区分流程跟踪与归档查询';

ALTER TABLE POSS_CUST_PAYMENT
   ADD CONSTRAINT FK_POSS_CUS_REFERENCE_POSS_ATT FOREIGN KEY (PAYMENT_RECEIPT_ID_)
      REFERENCES POSS_ATTACHMENT (ID_);

ALTER TABLE POSS_CUST_PAYMENT
   ADD CONSTRAINT FK_POSS_CUS_REFERENCE_POSS_PRO FOREIGN KEY (PROD_ID_)
      REFERENCES POSS_PROD_INFO (ID_);
	  

/*==============================================================*/
/* Table: "OA_TASK"                                             */
/*==============================================================*/
CREATE TABLE "POSS_TASK"  (
   ID_                  VARCHAR2(36)                    NOT NULL,
   "TASKINSTANCEID_"    VARCHAR2(36),
   "FLOWINSTANCEID_"    VARCHAR2(36),
   "FLOWKEY_"           VARCHAR2(36),
   "FLOWDEFINEID_"      VARCHAR2(36),
   "TASKSTATE_"         VARCHAR2(20),
   "FORMID_"            VARCHAR2(36),
   "TRANSACTOR_"        VARCHAR2(128),
   "CREATETIME_"        TIMESTAMP,
   "STARTTIME_"         TIMESTAMP,
   "ENDTIME_"           TIMESTAMP,
   "COMMENT_"           VARCHAR2(4000),
   "NODENAME_"          VARCHAR2(400),
   "TASKNAME_"          VARCHAR2(400),
   "FLOWNAME_"          VARCHAR2(400),
   "VIEWFLAG_"          SMALLINT,
   "DESCRIPTION_"       VARCHAR2(400),
   TASK_TYPE_			SMALLINT,
   FLOW_CLASS_			VARCHAR2(128),
   CONSTRAINT PK_POSS_TASK PRIMARY KEY (ID_)
);


/*==============================================================*/
/* Table: "OA_TASKASSIGN"                                       */
/*==============================================================*/
CREATE TABLE POSS_TASKASSIGN  (
   ID_                  VARCHAR2(36)                    NOT NULL,
   TASKID_            VARCHAR2(36),
   TYPE_             INTEGER,
   ASSIGNKEY_         VARCHAR2(128),
   CONSTRAINT PK_POSS_TASKASSIGN PRIMARY KEY (ID_)
);


ALTER TABLE "POSS_TASKASSIGN"
   ADD CONSTRAINT FK_TASKPOOLEDS_REF_TASKS FOREIGN KEY ("TASKID_")
      REFERENCES "POSS_TASK" (ID_);

	  
-- Create table
create table POSS_TASK_COMMENT
(
  id_         VARCHAR2(36) not null,
  creator_    VARCHAR2(128),
  addtime_    TIMESTAMP(6),
  task_class_ VARCHAR2(512),
  comment_    VARCHAR2(4000),
  task_id_    VARCHAR2(36),
  flag_       INTEGER default 0,
  data_type_  INTEGER default 0
);
-- Add comments to the columns 
comment on column POSS_TASK_COMMENT.flag_
  is '0,正常的处理意见
1,临时保存的处理意见';
comment on column POSS_TASK_COMMENT.data_type_
  is '0 任务处理说明
1 表单备注';
-- Create/Recreate primary, unique and foreign key constraints 
alter table POSS_TASK_COMMENT
  add constraint PK_POSS_TASK_COMMENT primary key (ID_);

alter table POSS_TASK_COMMENT
  add constraint FK_POSS_TASK_FK_TASK foreign key (TASK_ID_)
  references POSS_TASK (ID_);

/*==============================================================*/
/* Table: POSS_CUST_REFUND                                      */
/*==============================================================*/
CREATE TABLE POSS_CUST_REFUND  (
   ID_                  VARCHAR2(36)                    NOT NULL,
   PROD_ID_             VARCHAR2(36),
   SUPPLIER_            VARCHAR2(128),
   CUST_ID_             VARCHAR2(36),
   FLOW_TITLE_          VARCHAR2(128),
   PROPOSER_            VARCHAR2(36),
   PROPOSER_DEPT_       VARCHAR2(36),
   APPLY_TIME_          DATE,
   PAYMENT_ID_          VARCHAR2(36),
   FULL_REFUND_FLAG_    SMALLINT                       DEFAULT 1,
   REFUND_AMOUNT_       NUMBER(16,2),
   REFUND_REASON_       VARCHAR2(256),
   FLOW_INSTANCE_ID_    VARCHAR2(36),
   ARCHIVE_DATE_        TIMESTAMP,
   PASSED_              SMALLINT,
   FORM_STATUS_         VARCHAR2(36),
   CONSTRAINT PK_POSS_CUST_REFUND PRIMARY KEY (ID_)
);

COMMENT ON TABLE POSS_CUST_REFUND IS
'退款表单';

COMMENT ON COLUMN POSS_CUST_REFUND.ID_ IS
'主键';

COMMENT ON COLUMN POSS_CUST_REFUND.PROD_ID_ IS
'产品ID';

COMMENT ON COLUMN POSS_CUST_REFUND.SUPPLIER_ IS
'产品供应商';

COMMENT ON COLUMN POSS_CUST_REFUND.CUST_ID_ IS
'客户ID';

COMMENT ON COLUMN POSS_CUST_REFUND.FLOW_TITLE_ IS
'流程标题';

COMMENT ON COLUMN POSS_CUST_REFUND.PROPOSER_ IS
'申请人';

COMMENT ON COLUMN POSS_CUST_REFUND.PROPOSER_DEPT_ IS
'所在部门';

COMMENT ON COLUMN POSS_CUST_REFUND.APPLY_TIME_ IS
'申请时间';

COMMENT ON COLUMN POSS_CUST_REFUND.PAYMENT_ID_ IS
'划款表单ID';

COMMENT ON COLUMN POSS_CUST_REFUND.FULL_REFUND_FLAG_ IS
'是否全额退款';

COMMENT ON COLUMN POSS_CUST_REFUND.REFUND_AMOUNT_ IS
'退款金额';

COMMENT ON COLUMN POSS_CUST_REFUND.REFUND_REASON_ IS
'退款理由';

COMMENT ON COLUMN POSS_CUST_REFUND.FLOW_INSTANCE_ID_ IS
'流程实例ID';

COMMENT ON COLUMN POSS_CUST_REFUND.ARCHIVE_DATE_ IS
'归档时间';

COMMENT ON COLUMN POSS_CUST_REFUND.PASSED_ IS
'0 否
1 是';

COMMENT ON COLUMN POSS_CUST_REFUND.FORM_STATUS_ IS
'流程结束时为已归档状态
用于区分流程跟踪与归档查询';

ALTER TABLE POSS_CUST_REFUND
   ADD CONSTRAINT FK_PESS_CUS_REFERENCE_PESS_PRO FOREIGN KEY (PROD_ID_)
      REFERENCES POSS_PROD_INFO (ID_);
	  
/*==============================================================*/
/* Table: POSS_REFUND_ATTACH                                    */
/*==============================================================*/
CREATE TABLE POSS_REFUND_ATTACH  (
   CUST_REFUND_ID_      VARCHAR2(36)                    NOT NULL,
   ATTACH_ID_           VARCHAR2(36)                    NOT NULL,
   CONSTRAINT PK_POSS_REFUND_ATTACH PRIMARY KEY (CUST_REFUND_ID_, ATTACH_ID_)
);

COMMENT ON TABLE POSS_REFUND_ATTACH IS
'退款申请附件';

COMMENT ON COLUMN POSS_REFUND_ATTACH.CUST_REFUND_ID_ IS
'退款表单ID';

COMMENT ON COLUMN POSS_REFUND_ATTACH.ATTACH_ID_ IS
'附件ID';

ALTER TABLE POSS_REFUND_ATTACH
   ADD CONSTRAINT FK_POSS_REF_REFERENCE_POSS_CUS FOREIGN KEY (CUST_REFUND_ID_)
      REFERENCES POSS_CUST_REFUND (ID_);

ALTER TABLE POSS_REFUND_ATTACH
   ADD CONSTRAINT FK_POSS_REF_REFERENCE_POSS_ATT FOREIGN KEY (ATTACH_ID_)
      REFERENCES POSS_ATTACHMENT (ID_);
      
/*==============================================================*/
/* Table: POSS_PROD_ISSUE_PLAN                                  */
/*==============================================================*/
CREATE TABLE POSS_PROD_ISSUE_PLAN  (
   ID_                  VARCHAR2(36)                    NOT NULL,
   PROD_ID_             VARCHAR2(36),
   STD_ORDER_FLAG_      SMALLINT,
   SALES_MODEL_         VARCHAR(200),
   LOWEST_STD_          VARCHAR(50),
   REMAIN_AMOUNT_WARN_  VARCHAR(50),
   REMAIN_AMOUNT_STOP_  VARCHAR(50),
   SMALL_CAPS_          VARCHAR(50),
   SMALL_NUM_CAPS_      VARCHAR(50),
   DESCRIPTION_         VARCHAR(2000),
   MANAGER_TAKE_RATIO_  VARCHAR(50),
   PARTNER_TAKE_RATIO_  VARCHAR(50),
   BIG_AMOUNT_POINT_    VARCHAR(50),
   LOWEST_PAY_AMOUNT_   VARCHAR(50),
   SIZE_VOLUME_RATIO_   VARCHAR(50),
   BIG_TO_SMALL_FLAG_   SMALLINT,
   SMALL_APPOINT_FLAG_  SMALLINT,
   PREHEAT_START_TIME_  TIMESTAMP,
   PREHEAT_END_TIME_    TIMESTAMP,
   ESTIMATE_END_TIME_   TIMESTAMP,
   CONTRACT_SEND_TIME_  TIMESTAMP,
   DATA_SEND_TIME_      TIMESTAMP,
   PROD_TRAIN_TIME_     TIMESTAMP,
   NON_STD_START_TIME_  TIMESTAMP,
   NON_STD_AMOUNT_      VARCHAR(50),
   NON_STD_LIMIT_RATIO_ VARCHAR(50),
   ORDER_TIME_LIMIT_    VARCHAR(50),
   SMALL_NUM_LIMIT_     VARCHAR(50),
   NON_STD_CFM_MIN_     VARCHAR(50),
   ORDER_RULE_          VARCHAR(4000),
   CONSTRAINT PK_POSS_PROD_ISSUE_PLAN PRIMARY KEY (ID_)
);

COMMENT ON TABLE POSS_PROD_ISSUE_PLAN IS
'发行方案';

COMMENT ON COLUMN POSS_PROD_ISSUE_PLAN.ID_ IS
'主键';

COMMENT ON COLUMN POSS_PROD_ISSUE_PLAN.PROD_ID_ IS
'产品ID';

COMMENT ON COLUMN POSS_PROD_ISSUE_PLAN.STD_ORDER_FLAG_ IS
'是否允许进行标准预约';

COMMENT ON COLUMN POSS_PROD_ISSUE_PLAN.SALES_MODEL_ IS
'销售模式';

COMMENT ON COLUMN POSS_PROD_ISSUE_PLAN.LOWEST_STD_ IS
'最低成立标准（万）';

COMMENT ON COLUMN POSS_PROD_ISSUE_PLAN.REMAIN_AMOUNT_WARN_ IS
'剩余金额预警上限（%）';

COMMENT ON COLUMN POSS_PROD_ISSUE_PLAN.REMAIN_AMOUNT_STOP_ IS
'剩余金额叫停上限（%）';

COMMENT ON COLUMN POSS_PROD_ISSUE_PLAN.SMALL_CAPS_ IS
'小额上限';

COMMENT ON COLUMN POSS_PROD_ISSUE_PLAN.SMALL_NUM_CAPS_ IS
'控制小额数目上限';

COMMENT ON COLUMN POSS_PROD_ISSUE_PLAN.DESCRIPTION_ IS
'说明';

COMMENT ON COLUMN POSS_PROD_ISSUE_PLAN.MANAGER_TAKE_RATIO_ IS
'职业经理人提成比例';

COMMENT ON COLUMN POSS_PROD_ISSUE_PLAN.PARTNER_TAKE_RATIO_ IS
'合伙人提成比例';

COMMENT ON COLUMN POSS_PROD_ISSUE_PLAN.BIG_AMOUNT_POINT_ IS
'大额起点（万）';

COMMENT ON COLUMN POSS_PROD_ISSUE_PLAN.LOWEST_PAY_AMOUNT_ IS
'最低打款额度（万）';

COMMENT ON COLUMN POSS_PROD_ISSUE_PLAN.SIZE_VOLUME_RATIO_ IS
'大小额配比';

COMMENT ON COLUMN POSS_PROD_ISSUE_PLAN.BIG_TO_SMALL_FLAG_ IS
'有无大额换小额';

COMMENT ON COLUMN POSS_PROD_ISSUE_PLAN.SMALL_APPOINT_FLAG_ IS
'有无小额指定';

COMMENT ON COLUMN POSS_PROD_ISSUE_PLAN.PREHEAT_START_TIME_ IS
'预热开始时间';

COMMENT ON COLUMN POSS_PROD_ISSUE_PLAN.PREHEAT_END_TIME_ IS
'预热结束时间';

COMMENT ON COLUMN POSS_PROD_ISSUE_PLAN.ESTIMATE_END_TIME_ IS
'预计结束时间';

COMMENT ON COLUMN POSS_PROD_ISSUE_PLAN.CONTRACT_SEND_TIME_ IS
'合同寄送时间';

COMMENT ON COLUMN POSS_PROD_ISSUE_PLAN.DATA_SEND_TIME_ IS
'募集账号和有账号资料发送时间';

COMMENT ON COLUMN POSS_PROD_ISSUE_PLAN.PROD_TRAIN_TIME_ IS
'产品视频培训时间';

COMMENT ON COLUMN POSS_PROD_ISSUE_PLAN.NON_STD_START_TIME_ IS
'非标开始时间';

COMMENT ON COLUMN POSS_PROD_ISSUE_PLAN.NON_STD_AMOUNT_ IS
'预计非标额度';

COMMENT ON COLUMN POSS_PROD_ISSUE_PLAN.NON_STD_LIMIT_RATIO_ IS
'非标额度限制比例';

COMMENT ON COLUMN POSS_PROD_ISSUE_PLAN.ORDER_TIME_LIMIT_ IS
'排序时间限制(分钟)';

COMMENT ON COLUMN POSS_PROD_ISSUE_PLAN.SMALL_NUM_LIMIT_ IS
'小额数量限制';

COMMENT ON COLUMN POSS_PROD_ISSUE_PLAN.NON_STD_CFM_MIN_ IS
'非标确认时间(分钟)';

COMMENT ON COLUMN POSS_PROD_ISSUE_PLAN.ORDER_RULE_ IS
'排序规则';

ALTER TABLE POSS_PROD_ISSUE_PLAN
   ADD CONSTRAINT FK_ISSPLAN_REFERENCE_POSS_PRO FOREIGN KEY (PROD_ID_)
      REFERENCES POSS_PROD_INFO (ID_); 
      
      
      
      
      
   
/*==============================================================*/
/* Table: POSS_BLANK_CONTRACT                                   */
/*==============================================================*/
CREATE TABLE POSS_BLANK_CONTRACT  (
   ID_                  VARCHAR2(36)                    NOT NULL,
   PROD_ID_             VARCHAR2(36),
   REG_NUMS_            NUMBER(3),
   CONTRACT_NUMS_       NUMBER(5),
   REMAIN_NUMS_         NUMBER(5),
   LATEST_DAYS_         NUMBER(3),
   RETURN_FLAG_         SMALLINT,
   CONSTRAINT PK_POSS_BLANK_CONTRACT PRIMARY KEY (ID_)
);

COMMENT ON TABLE POSS_BLANK_CONTRACT IS
'空白合同汇总';

COMMENT ON COLUMN POSS_BLANK_CONTRACT.ID_ IS
'主键';

COMMENT ON COLUMN POSS_BLANK_CONTRACT.PROD_ID_ IS
'产品ID';

COMMENT ON COLUMN POSS_BLANK_CONTRACT.REG_NUMS_ IS
'登记次数';

COMMENT ON COLUMN POSS_BLANK_CONTRACT.CONTRACT_NUMS_ IS
'合同总数';

COMMENT ON COLUMN POSS_BLANK_CONTRACT.REMAIN_NUMS_ IS
'剩余总数';

COMMENT ON COLUMN POSS_BLANK_CONTRACT.LATEST_DAYS_ IS
'最迟上交天数';

COMMENT ON COLUMN POSS_BLANK_CONTRACT.RETURN_FLAG_ IS
'是否盖章返还';




/*==============================================================*/
/* Table: POSS_CONTRACT_REG_DETAIL                              */
/*==============================================================*/
CREATE TABLE POSS_CONTRACT_REG_DETAIL  (
   ID_                  VARCHAR2(36)                    NOT NULL,
   CONTRACT_ID_         VARCHAR2(36),
   CONTRACT_NUMS_       NUMBER(5),
   REG_USER_            VARCHAR2(100),
   REG_DATE_            TIMESTAMP,
   CONSTRAINT PK_POSS_CONTRACT_REG_DETAIL PRIMARY KEY (ID_)
);

COMMENT ON TABLE POSS_CONTRACT_REG_DETAIL IS
'合同登记明细';

COMMENT ON COLUMN POSS_CONTRACT_REG_DETAIL.ID_ IS
'主键';

COMMENT ON COLUMN POSS_CONTRACT_REG_DETAIL.CONTRACT_ID_ IS
'合同汇总ID';

COMMENT ON COLUMN POSS_CONTRACT_REG_DETAIL.CONTRACT_NUMS_ IS
'合同数';

COMMENT ON COLUMN POSS_CONTRACT_REG_DETAIL.REG_USER_ IS
'登记人';

COMMENT ON COLUMN POSS_CONTRACT_REG_DETAIL.REG_DATE_ IS
'登记时间';



ALTER TABLE POSS_BLANK_CONTRACT
   ADD CONSTRAINT FK_CONTRACT_REF_PROD FOREIGN KEY (PROD_ID_)
      REFERENCES POSS_PROD_INFO (ID_);
      
ALTER TABLE POSS_CONTRACT_REG_DETAIL
   ADD CONSTRAINT FK_CON_DETAL_REF_BLANK_CON FOREIGN KEY (CONTRACT_ID_)
      REFERENCES POSS_BLANK_CONTRACT (ID_);




/*==============================================================*/
/* Table: POSS_CONTRACT_REQUEST                                 */
/*==============================================================*/
CREATE TABLE POSS_CONTRACT_REQUEST  (
   ID_                  VARCHAR2(36)                    NOT NULL,
   PROD_ID_             VARCHAR2(36),
   REG_STATUS_          SMALLINT,
   ORG_NAME_            VARCHAR2(100),
   REQ_NUMS_            NUMBER(5),
   EXTEND_NUMS_         NUMBER(5),
   REG_USER_            VARCHAR2(100),
   REG_DATE_            TIMESTAMP,
   REG_DEPT_            VARCHAR2(100),
   EXPRESS_NAME_        VARCHAR2(100),
   EXPRESS_NO_          VARCHAR2(100),
   SEND_DATE_           TIMESTAMP,
   REQ_REMARK_          VARCHAR2(2000),
   EXTEND_REMARK_       VARCHAR2(2000),
   EXTEND_DATE_         TIMESTAMP,
   FIRST_FLAG_          SMALLINT,
   CONSTRAINT PK_POSS_CONTRACT_REQUEST PRIMARY KEY (ID_)
);

COMMENT ON TABLE POSS_CONTRACT_REQUEST IS
'机构合同需求';

COMMENT ON COLUMN POSS_CONTRACT_REQUEST.ID_ IS
'主键';

COMMENT ON COLUMN POSS_CONTRACT_REQUEST.PROD_ID_ IS
'产品ID';

COMMENT ON COLUMN POSS_CONTRACT_REQUEST.REG_STATUS_ IS
'登记状态';

COMMENT ON COLUMN POSS_CONTRACT_REQUEST.ORG_NAME_ IS
'所属机构';

COMMENT ON COLUMN POSS_CONTRACT_REQUEST.REQ_NUMS_ IS
'所需合同数';

COMMENT ON COLUMN POSS_CONTRACT_REQUEST.EXTEND_NUMS_ IS
'实际发放数';

COMMENT ON COLUMN POSS_CONTRACT_REQUEST.REG_USER_ IS
'登记人';

COMMENT ON COLUMN POSS_CONTRACT_REQUEST.REG_DATE_ IS
'登记时间';

COMMENT ON COLUMN POSS_CONTRACT_REQUEST.REG_DEPT_ IS
'登记部门';

COMMENT ON COLUMN POSS_CONTRACT_REQUEST.EXPRESS_NAME_ IS
'快递公司名称';

COMMENT ON COLUMN POSS_CONTRACT_REQUEST.EXPRESS_NO_ IS
'配送快递单号';

COMMENT ON COLUMN POSS_CONTRACT_REQUEST.SEND_DATE_ IS
'配送时间';

COMMENT ON COLUMN POSS_CONTRACT_REQUEST.REQ_REMARK_ IS
'需求备注';

COMMENT ON COLUMN POSS_CONTRACT_REQUEST.EXTEND_REMARK_ IS
'发放备注';

COMMENT ON COLUMN POSS_CONTRACT_REQUEST.EXTEND_DATE_ IS
'发放时间';

COMMENT ON COLUMN POSS_CONTRACT_REQUEST.FIRST_FLAG_ IS
'是否首次登记';

ALTER TABLE POSS_CONTRACT_REQUEST
   ADD CONSTRAINT FK_CON_REQ_REF_PROD_INFO FOREIGN KEY (PROD_ID_)
      REFERENCES POSS_PROD_INFO (ID_);



/*==============================================================*/
/* Table: POSS_CONTRACT_HAND                                    */
/*==============================================================*/
CREATE TABLE POSS_CONTRACT_HAND  (
   ID_                  VARCHAR2(36)                    NOT NULL,
   PROD_ID_             VARCHAR2(36),
   CHECK_STATUS_        SMALLINT,
   ORG_NAME_            VARCHAR2(100),
   REG_USER_            VARCHAR2(100),
   REG_DATE_            TIMESTAMP,
   REG_DEPT_            VARCHAR2(100),
   EXPRESS_NAME_        VARCHAR2(100),
   EXPRESS_NO_          VARCHAR2(100),
   HAND_DATE_           TIMESTAMP,
   HAND_REMARK_         VARCHAR2(2000),
   SIGN_NUMS_           NUMBER(5),
   BLANK_NUMS_          NUMBER(5),
   INVALID_NUMS_        NUMBER(5),
   UNPASS_NUMS_         NUMBER(5),
   CHECK_REMARK_        VARCHAR2(2000),
   CHECK_DATE_          TIMESTAMP,
   CONSTRAINT PK_POSS_CONTRACT_HAND PRIMARY KEY (ID_)
);

COMMENT ON TABLE POSS_CONTRACT_HAND IS
'机构合同上交';

COMMENT ON COLUMN POSS_CONTRACT_HAND.ID_ IS
'主键';

COMMENT ON COLUMN POSS_CONTRACT_HAND.PROD_ID_ IS
'产品ID';

COMMENT ON COLUMN POSS_CONTRACT_HAND.CHECK_STATUS_ IS
'审核状态';

COMMENT ON COLUMN POSS_CONTRACT_HAND.ORG_NAME_ IS
'所属机构';

COMMENT ON COLUMN POSS_CONTRACT_HAND.REG_USER_ IS
'登记人';

COMMENT ON COLUMN POSS_CONTRACT_HAND.REG_DATE_ IS
'登记时间';

COMMENT ON COLUMN POSS_CONTRACT_HAND.REG_DEPT_ IS
'登记部门';

COMMENT ON COLUMN POSS_CONTRACT_HAND.EXPRESS_NAME_ IS
'快递公司名称';

COMMENT ON COLUMN POSS_CONTRACT_HAND.EXPRESS_NO_ IS
'上交快递单号';

COMMENT ON COLUMN POSS_CONTRACT_HAND.HAND_DATE_ IS
'上交时间';

COMMENT ON COLUMN POSS_CONTRACT_HAND.HAND_REMARK_ IS
'上交备注';

COMMENT ON COLUMN POSS_CONTRACT_HAND.SIGN_NUMS_ IS
'签署合同数';

COMMENT ON COLUMN POSS_CONTRACT_HAND.BLANK_NUMS_ IS
'空白合同数';

COMMENT ON COLUMN POSS_CONTRACT_HAND.INVALID_NUMS_ IS
'签废合同数';

COMMENT ON COLUMN POSS_CONTRACT_HAND.UNPASS_NUMS_ IS
'不通过合同数';

COMMENT ON COLUMN POSS_CONTRACT_HAND.CHECK_REMARK_ IS
'审核备注';

COMMENT ON COLUMN POSS_CONTRACT_HAND.CHECK_DATE_ IS
'审核时间';

ALTER TABLE POSS_CONTRACT_HAND
   ADD CONSTRAINT FK_CON_HAND_REF_PROD_INFO FOREIGN KEY (PROD_ID_)
      REFERENCES POSS_PROD_INFO (ID_);


/*==============================================================*/
/* Table: POSS_CONFIRM_EXTEND                                   */
/*==============================================================*/
CREATE TABLE POSS_CONFIRM_EXTEND  (
   ID_                  VARCHAR2(36)                    NOT NULL,
   PROD_ID_             VARCHAR2(36),
   ORG_NAME_            VARCHAR2(100),
   CUST_NUMS_            NUMBER(5),
   CONFIRM_NUMS_        NUMBER(5),
   EXPRESS_NAME_        VARCHAR2(100),
   EXPRESS_NO_          VARCHAR2(100),
   REMARK_              VARCHAR2(2000),
   REG_USER_            VARCHAR2(100),
   REG_DATE_            TIMESTAMP,
   REG_DEPT_            VARCHAR2(100),
   CONSTRAINT PK_POSS_CONFIRM_EXTEND PRIMARY KEY (ID_)
);

COMMENT ON TABLE POSS_CONFIRM_EXTEND IS
'确认书发放';

COMMENT ON COLUMN POSS_CONFIRM_EXTEND.ID_ IS
'主键';

COMMENT ON COLUMN POSS_CONFIRM_EXTEND.PROD_ID_ IS
'产品ID';

COMMENT ON COLUMN POSS_CONFIRM_EXTEND.ORG_NAME_ IS
'所属机构';

COMMENT ON COLUMN POSS_CONFIRM_EXTEND.CUST_NUMS_ IS
'客户数';

COMMENT ON COLUMN POSS_CONFIRM_EXTEND.CONFIRM_NUMS_ IS
'确认书数目';

COMMENT ON COLUMN POSS_CONFIRM_EXTEND.EXPRESS_NAME_ IS
'快递公司';

COMMENT ON COLUMN POSS_CONFIRM_EXTEND.EXPRESS_NO_ IS
'快递单号';

COMMENT ON COLUMN POSS_CONFIRM_EXTEND.REMARK_ IS
'备注';

COMMENT ON COLUMN POSS_CONFIRM_EXTEND.REG_USER_ IS
'登记人';

COMMENT ON COLUMN POSS_CONFIRM_EXTEND.REG_DATE_ IS
'登记时间';

COMMENT ON COLUMN POSS_CONFIRM_EXTEND.REG_DEPT_ IS
'登记部门';

ALTER TABLE POSS_CONFIRM_EXTEND
   ADD CONSTRAINT FK_CONF_EXT_REF_PROD_INFO FOREIGN KEY (PROD_ID_)
      REFERENCES POSS_PROD_INFO (ID_);

